### ISSUE TITLE
Support mkv files

### ISSUE THREAD

**Issue by johan456789** [shadowmoose/Web-Video-Editor#1]
Is it possible to support mkv files?

**Comment by shadowmoose** [comment]
Support in what way? In chrome, I am able to load mkv files into the editor. I did have to change the file type in the selector to allow "All Files" though.

**Comment by johan456789** [comment]
I didn't know that. Weird that mkv file is not “Video Files” in Finder. It does load the mkv file, but it generates command that outputs to mp4, which might leads to unsuccessful conversion.

So 2 slight improvements IMO:
1. Use "All Files" by default
2. Output as mkv if the input is mkv (or more generally output as the same file type as the input)

**Comment by shadowmoose** [comment]
Expanded the file list to support pretty much all video files, and preserved the original file name and extension for the output file.
